export const images = {
  splash: require('./splash.png'),
  loginBackground: require('./loginBackground.png'),
  logo: require('./logo.png'),
  signUpBackground: require('./signUpBackground.png'),
  backArrow: require('./backArrow.png'),
  purpleInputError: require('./purpleInputError.png'),
  whiteInputError: require('./whiteInputError.png'),
  forgotPassword: require('./forgotPassword.png'),
  facebook: require('./facebook.png'),
  homeIconActive: require('./homeIconActive.png'),
  chatsIconInactive: require('./chatsIconInactive.png'),
  profileIconInactive: require('./profileIconInactive.png'),
  petSettingsIcon: require('./petSettingsIcon.png'),
  settingsIcon: require('./settingsIcon.png'),
  aboutIcon: require('./aboutIcon.png'),
  helpIcon: require('./helpIcon.png'),
  termsIcon: require('./termsIcon.png'),
  privacyIcon: require('./privacyIcon.png'),
  accountIcon: require('./accountIcon.png'),
  logoutIcon: require('./logoutIcon.png'),
};
